### ISSUE TITLE
RDA-VOC: all submissions failed to parse

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#10]
This ontology was created in November of 2016 and none of the submissions ever parsed.  The user entered a pull URL that points to and HTML page (http://www.rdaregistry.info/termList/) instead of an ontology source file.  All submissions should be deleted.

**Comment by jvendetti** [comment]
Deleted all 5 invalid submissions.

**Comment by graybeal** [comment]
An added note, this is work I'm doing with people in the Stanford libraries. I don't know if you email the authors routinely, but if not I'll contact them to see if they need help on this.

**Comment by jvendetti** [comment]
@graybeal - no, I haven't contacted the maintainers.

**Comment by graybeal** [comment]
I contacted Nancy Lorimer, the SDR person who added this. Will work with her.
