### ISSUE TITLE
update BioPortal front page

### ISSUE THREAD

**Issue by graybeal** [ncbo/bioportal-project#103]
Create a new BioPortal front page (to be accessed at www.bioontology.org) that follows the general form of the Protege front page (protege.stanford.edu).

Following requests subject to team's suggested improvements.

Proposed text for above the fold page: 

```
A free, open-source community repository and toolset for biomedical and scientific knowledge 
resources
```

and

```
BioPortal solutions are used by tens of thousands of academic, government, and corporate users 
to contribute, discover, and apply FAIR scientific knowledge artifacts. Our user and application 
interfaces provide real-time access to the latest resources and technologies, 
and can be deployed in your own customized environments.
```

Top buttons should be "Use BioPortal" and "Get Technical Details"

"Used by" line should be "Serving # user requests and # software requests per week", to be populated by New Relic statistics, if we can find a way to do that automagically. If not let's talk about what instead.

If we can pull testimonials from the list (with permission), use those for the testimonials section.

"Look no further…" text replaced by "Start here to learn more", and point to www.bioontology.org/wiki.

Why Protege becomes BioPortal Capabilities, with Semantic Resources, Advanced Tools, and Customized Versions (text to be provided).

**Comment by jvendetti** [comment]
@graybeal - now that the [BioPortal site](https://www.bioontology.org/) is live, is it acceptable to close this issue? The initial UI doesn't resemble the Protege website as requested above, but I'm under the impression it's acceptable as-is for the moment, and will be developed iteratively going forward by a mix of team members.

**Comment by graybeal** [comment]
Yup! Closing now
