### ISSUE TITLE
NEO: fails to load

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#111]
The [NEO ontology](http://bioportal.bioontology.org/ontologies/NEO) shows "Error Rdf" status in the BioPortal UI. Stack trace from parsing log file:

```
E, [2019-04-22T11:27:38.785943 #5770] ERROR -- : ["Exception: could not `LANG=C grep -v '_:genid' /tmp/file_nobnodes20190422-5770-1hw2ajk/data.nt > /tmp/file_nobnodes20190422-5770-1hw2ajk/data_no_bnodes.nt`: 
/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/goo-0bc8c933f3f8/lib/goo/sparql/client.rb:66:in `bnodes_filter_file'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/goo-0bc8c933f3f8/lib/goo/sparql/client.rb:81:in `append_triples_no_bnodes'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/goo-0bc8c933f3f8/lib/goo/sparql/client.rb:129:in `put_triples'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ontologies_linked_data-548e7b1e4fb8/lib/ontologies_linked_data/models/ontology_submission.rb:1529:in `delete_and_append'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ontologies_linked_data-548e7b1e4fb8/lib/ontologies_linked_data/models/ontology_submission.rb:475:in `generate_rdf'
	/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.5.0/bundler/gems/ontologies_linked_data-548e7b1e4fb8/lib/ontologies_linked_data/models/ontology_submission.rb:973:in `process_submission'
	/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:177:in `process_submission'
	bin/ncbo_ontology_process:98:in `block in <main>'
	bin/ncbo_ontology_process:81:in `each'
	bin/ncbo_ontology_process:81:in `<main>'"]
```

Oddly, the owlapi.xrdf file is well formed, but lacks any ontology data:

```
<?xml version="1.0"?>
<rdf:RDF xmlns="http://www.w3.org/2002/07/owl#"
     xml:base="http://www.w3.org/2002/07/owl"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
    <Ontology/>
</rdf:RDF>

<!-- Generated by the OWL API (version 4.3.2) https://github.com/owlcs/owlapi -->
```

**Comment by jvendetti** [comment]
Downloaded the OWL file (NEO8.owl) and ran it through the owlapi_wrapper project in my local development environment. The problem with an empty owlapi.xrdf file wasn't reproducible. The resulting file is 489K and contains ontology data:

```
<?xml version="1.0"?>
<rdf:RDF xmlns="http://www.w3.org/2002/07/owl#"
     xml:base="http://www.w3.org/2002/07/owl"
     xmlns:metadata="http://data.bioontology.org/metadata/"
     xmlns:webprotege="http://webprotege.stanford.edu/"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:skos="http://www.w3.org/2004/02/skos/core#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     xmlns:BbHRvdgdu3Y4vbyVxXTwfu="http://webprotege.stanford.edu/project/BbHRvdgdu3Y4vbyVxXTwfu#"
     xmlns:dc="http://purl.org/dc/elements/1.1/">
    <Ontology/>

    <!-- 
    ///////////////////////////////////////////////////////////////////////////////////////
    //
    // Annotation properties
    //
    ///////////////////////////////////////////////////////////////////////////////////////
     -->

    <!-- http://data.bioontology.org/metadata/prefixIRI -->

    <AnnotationProperty rdf:about="http://data.bioontology.org/metadata/prefixIRI"/>

    <!-- http://purl.org/dc/elements/1.1/description -->

    <AnnotationProperty rdf:about="http://purl.org/dc/elements/1.1/description"/>

    ... etc.
```

**Comment by graybeal** [comment]
Is this possibly a case where there is a file system problem that keeps the output file from being created, or added to?

**Comment by jvendetti** [comment]
@graybeal - no, I checked that. The owlapi.xrdf file is successfully created and contains some minimal number of lines (see the initial issue comment). The file has the correct owner and permissions set.

**Comment by jvendetti** [comment]
After some prolonged investigation, I've discovered that the OWL API code for loading this ontology produces a different result depending on the method of program execution. In other words, executing the following few lines of code from an IDE:

```
File file = new File("src/main/resources/NEO.owl");
FileDocumentSource fileDocumentSource = new FileDocumentSource(file);
OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
OWLOntologyLoaderConfiguration conf = new OWLOntologyLoaderConfiguration();
conf = conf.setMissingImportHandlingStrategy(MissingImportHandlingStrategy.THROW_EXCEPTION);
OWLOntology ontology = manager.loadOntologyFromOntologyDocument(fileDocumentSource, conf);
```
... results in an ontology object that reports 3303 axioms. However, if you create a small Java program that contains the identical code, JAR it up, and run it from the command line, you'll get an ontology object that reports zero axioms. I developed a small Maven project in IntelliJ with the code above, and targets for generating a JAR file that can be launched from the command line. Attaching it here so that we have a documented / reproducible case. 
[owlapi-neo-ont.zip](https://github.com/ncbo/bioportal-project/files/3129441/owlapi-neo-ont.zip)

I've also entered an issue in the owlapi tracker (https://github.com/owlcs/owlapi/issues/842), asking if they have any insight on this behavior.

**Comment by jvendetti** [comment]
Published a [new release](https://github.com/ncbo/owlapi_wrapper/releases/tag/v1.3.4) of the owlapi_wrapper to address the issue described in the previous comment. The new version produces a descriptive error message that helped to uncover a syntax error in the NEO ontology (a skos:definition with a missing end tag on line 1033). The end user has since submitted a new version of the ontology that fixes the syntax error. 

The new owlapi_wrapper (v1.3.4) will be deployed to production with the next backend release.
