### ISSUE TITLE
Can't load SWEET, getting 403 error

### ISSUE THREAD

**Issue by graybeal** [ncbo/bioportal-project#127]
There's a ticket for this at https://github.com/ESIPFed/sweet/issues/150, this is to reference that ticket as it affects BioPortal loading of SWEET.

**Comment by carueda** [comment]
In particular, this comment about the diagnosis of the problem: https://github.com/ESIPFed/sweet/issues/150#issuecomment-514337050

EDIT: I'd add here that this is not strictly speaking a bioportal/protege/owlapi issue -- the 403 is indeed reported from the SWEET server - the issue is that a certain "middleware" there (cloudflare) doesn't like the `User-Agent:Java/1.8.0_40` request header sent from these clients.

**Comment by jvendetti** [comment]
As a temporary workaround to make SWEET 3.3.0 accessible in BioPortal, I performed the following steps:

1. Downloaded a local copy of [sweetAll.ttl](https://github.com/ESIPFed/sweet/blob/master/src/sweetAll.ttl) (and all associated imports) from the [ESIPFed/sweet](https://github.com/ESIPFed/sweet) repository.
2. Downloaded a [catalog-v00.xml](https://github.com/ESIPFed/sweet/blob/issue-147/src/catalog-v001.xml) file from ESIPFed that facilitates being able to open the local copy in Protege. See https://github.com/ESIPFed/sweet/issues/147.
3. Used the Protege application (v 5.5.0) to merge all imports into a single ontology file, and uploaded that file to BioPortal.

The [classes tab](http://bioportal.bioontology.org/ontologies/SWEET/?p=classes) now displays a class hierarchy.

**Comment by jvendetti** [comment]
I modified my local dev environment to use Open JDK 12 (production BioPortal uses Java 8). With this newer version of Java, the following test case for loading SWEET:

```
File file = new File("/Users/jvendetti/Development/GitHub/sweet/src/sweetAll.ttl");
FileDocumentSource fileDocumentSource = new FileDocumentSource(file);
OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
OWLOntology ontology = manager.loadOntologyFromOntologyDocument(fileDocumentSource);
```
... doesn't result in the 403 responses. All unit tests pass in the [owlapi_wrapper project](https://github.com/ncbo/owlapi_wrapper) against Java 12. I don't see any reason why we couldn't upgrade that portion of the codebase to the latest Java. 

@alexskr - are you aware of any roadblocks with our production machines that would prevent us from upgrading to Open JDK 12?

**Comment by alexskr** [comment]
It would be better to use Open JDK 11 because it is LTS.

**Comment by graybeal** [comment]
Cloudflare has updated their settings and Protege doesn't have any more trouble with the SWEET ontology. Just need to confirm BioPortal works now and fix the auto-download setting.

**Comment by jvendetti** [comment]
I modified SWEET in BioPortal to use the load from URL functionality again (http://sweetontology.net/sweetALL). Processing completed successfully.
