### ISSUE TITLE
update new OBO Library ontologies in BioPortal

### ISSUE THREAD

**Issue by graybeal** [ncbo/bioportal-project#135]
The list of ontologies from OBO that aren't in BioPortal has grown, the following OBO Library ontologies are missing from BioPortal (italicized ontologies were missing March 2018, so may be 'known issues'):

apollo_sv (Apollo Structured Vocabulary)
*aro (Antibiotic Resistance Ontology)*
*cro (Contributor Role Ontology) *
*dpo (Drosophila Phenotype Ontology) *
*ecocore (An ontology of core ecological entities) *
*eupath (EuPathDB ontology) *
hancestro (Human Ancestry Ontology)
htn (Hypertension Ontology)
ino (Interaction Network Ontology)
mco (Microbial Conditions Ontology)
*mpio (Minimum PDDI Information Ontology) *
nomen (NOMEN - A nomenclatural ontology for biological names)
ohpi (Ontology of Host Pathogen Interactions)
opmi (Ontology of Precision Medicine and Investigation)
ornaseq (Ontology of RNA Sequencing)
*peco (Plant Experimental Conditions Ontology) *
phipo (Pathogen Host Interaction Phenotype Ontology)
planp (Planarian Phenotype Ontology)
psdo (Performance Summary Display Ontology)
*sepio (Scientific Evidence and Provenance Information Ontology) *
xlmod (HUPO-PSI cross-linking and derivatization reagents controlled vocabulary)
xpo (Xenopus Phenotype Ontology)
zp (Zebrafish Phenotype Ontology)
upa (Unipathway)

**Comment by jvendetti** [comment]
Started documenting our process for keeping the OBO Foundry and BioPortal in sync here: https://github.com/ncbo/documentation/wiki/Synchronization-with-the-OBO-Foundry.

**Comment by jvendetti** [comment]
The mapping of BioPortal ontology acronyms to OBO Foundry ID spaces is now maintained in a [JSON file](https://github.com/ncbo/ncbo.github.io/blob/master/oboids_to_bpacronyms.json), external to the [ncbo_cron](https://github.com/ncbo/ncbo_cron) repository. The mappings were previously hard coded in a Hash object.
