### ISSUE TITLE
can't access found term

### ISSUE THREAD

**Issue by graybeal** [ncbo/bioportal-project#139]
When doing a search for "NM, lung scan, ventilation/perfusion" in CPT from the (advanced) Search for terms dialog (front page) I find the link in the image below, which doesn't actually resolve when I click on it.

http://bioportal.bioontology.org/ontologies/CPT?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FCPT%2F78582

![Screen Shot 2019-11-18 at 10.51.50 AM.png](https://images.zenhubusercontent.com/5cc9bdc26c1fd80bacaab82a/46dbfc5b-ae7b-415a-84e9-7ae46165971e)

**Comment by mdorf** [comment]
I'm not able to reproduce this.

**Comment by mdorf** [comment]
This behavior appears random (some of the times, the links work, and other times they don't) and affects ALL searches on CPT.

**Comment by jvendetti** [comment]
Problem is reproducible on all searches with all ontologies. It has to do with the position where the end user clicks on the links. If you click on the left-hand side of the link, i.e., the term name that is listed before the dash character, the UI shows a 404 error. If you click on the right-hand side of the link, i.e., the ontology name after the dash character, the UI correctly navigates to the term in the ontology class tree.
