### ISSUE TITLE
run spam script and spot-check

### ISSUE THREAD

**Issue by graybeal** [ncbo/bioportal-project#150]
Just in case the outage relates to spamming, run the spam deletion script and check for any unexpected content.

**Comment by alexskr** [comment]
the spam scrip we have in place simply purges all records created by a specific user;  it doesn't detect spam content on its own.  
tools like https://github.com/joshfrench/rakismet could help with identifying and filtering out spam.

Noes, projects and ontology reviews have been spot-checked and ~4 users who created spam have been purged.

**Comment by mdorf** [comment]
Script has been executed and several additional records have been removed manually.
