### ISSUE TITLE
Display New Term Request form in PR

### ISSUE THREAD

**Issue by graybeal** [ncbo/bioportal-project#159]
Figure out the best short-term way to display the New Term Request form for the PR ontology (http://bioportal.bioontology.org/ontologies/PR).  

See also https://github.com/ncbo/bioportal-project/issues/157 and https://github.com/ncbo/bioportal-project/issues/158 for longer-term challenges.

**Comment by jvendetti** [comment]
@mdorf - I created a new submission for PR which reverts back to OBO format (#158).

Question: is the New Term Request tab supposed to show up for all users of public BioPortal, including unauthenticated?

**Comment by mdorf** [comment]
This behavior is by design. Users are prompted to log in once they click on the "Request New Term" link.

**Comment by jvendetti** [comment]
Thanks for the clarification @mdorf. Can we mark this as closed then?

**Comment by mdorf** [comment]
Closed
