### ISSUE TITLE
Load UMLS 2020AA

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#166]
We've received interest in this upcoming release from two people on the support list. There's apparently a new version of the MedDRA ontology (23.0) that has COVID-19 related terms and revisions.

**Comment by graybeal** [comment]
It turns out MedDRA 23.0 isn't in 2020AA, so that reduced the rush. But we still want to upload this. Alex suggests he can get to it in 2-3 weeks.

**Comment by jvendetti** [comment]
We need to remove the CPT ontology as part of the 2020AA import. See https://github.com/ncbo/bioportal-project/issues/170, and https://github.com/ncbo/umls2rdf/issues/34.
