### ISSUE TITLE
Add custom fields to ontologies that are displayed and used in the UI

### ISSUE THREAD

**Issue by mdorf** [ncbo/bioportal-project#179]
1. A field to allow a custom message to be displayed on the ontology homepage.
2. A field to provide special instructions on how to submit requests for new terms in the ontology (see OntoloBridge/ontolobridge-project#76)

**Comment by graybeal** [comment]
The field to allow a custom message to be displayed on the ontology home page is just to 'reserve the space'—no front-end implementation is expected at this time. 

However, if the UI for changing the information in the term request page can be trivially adapted to also allow changing the value in the custom ontology message field, making both available at the same time would be dandy.

**Comment by jonquet** [comment]
The first point seems to be a UI customization. I would recommend to use a metadata field for this such as omv:description.

For the second point, Dublin Core Terms defines 3 properties for this 
https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/accrualMethod 
These are the 3 properties we have added in AgroPortal's ontology metadata model. 
I would recommend to use the same ones. 
Note that they are barely used.

**Comment by graybeal** [comment]
Both of these are envisioned as BioPortal-specific information. I do not expect either to be in the ontology, they are not meaningful in that role.

**Comment by mdorf** [comment]
@graybeal, usually, any ontology or submission specific fields are added to the corresponding model. I believe we already have a number of BioPortal specific fields in these models. Did you imply storing them using different means?

**Comment by mdorf** [comment]
Implemented, deployed to production
