### ISSUE TITLE
BioPortal SPARQL: no results for NIFSTD ontology

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#18]
Question from the support list ([view in archive](https://mailman.stanford.edu/pipermail/bioontology-support/2017-April/009454.html)):

"Is the NIFSTD on BioPortal query endpoint just outdated or is it not loaded anymore? Because I ran 2 queries which did not retrieve any results. I want to know if queries were wrong or they did not retrieve results since the ontology was not loaded."

Note that [NIFSTD](http://bioportal.bioontology.org/ontologies/NIFSTD) isn't a private ontology, and it's been in BioPortal since 2008.

**Comment by alexskr** [comment]
BioPortal open SPARQL endpoint has been deprecated

**Comment by syphax-bouazzouni** [comment]
hello, just out of curiosity, how was it working then? (a copy of production or direct access) and do you know why the deprecation?  (a lack of time, lack of real usage, or a technical limitation)

**Comment by jvendetti** [comment]
Hi Syhpax. It was a copy of production data, not direct access.

A number of years ago I had a conversation with the original developer working on the endpoint (Manuel Salvadores), and he characterized it as difficult to maintain. He indicated there were no restrictions on the sort of SPARQL queries that users could issue against the endpoint. Periodically users would issue complex queries that the endpoint couldn't handle, resulting in downtime.

In more recent years, I think the deprecation has been favored because of lack of time / resources. There have been a number of internal discussions about resurrecting the open SPARQL endpoint after transitioning to a new triplestore, but there were no conclusions.

Unless there are objections, I plan to close this issue in favor of further discussion on this topic occurring in a newer ticket that's not specific to NIFSTD: https://github.com/ncbo/bioportal-project/issues/290.
