### ISSUE TITLE
try including German MedDRA in UMLS import

### ISSUE THREAD

**Issue by graybeal** [ncbo/bioportal-project#194]
I think this will involve adding the German MedDRA to the list of ontologies to process, and probably adding a page for it. Alex may know of other specific tasks.

**Comment by alexskr** [comment]
Added MDRGER in umls2rdf config and added to bioportal. 
https://github.com/ncbo/umls2rdf/commit/d51760b572505241eec3b0728ceef8d28909630

**Comment by alexskr** [comment]
MDRGER is loaded in production
http://bioportal.bioontology.org/ontologies/MDRGER
