### ISSUE TITLE
FDC-GDMT wrongly shown as no submissions

### ISSUE THREAD

**Issue by graybeal** [ncbo/bioportal-project#199]
The FDC-GDMT ontology has a number of submissions, as shown below. But the Admin page thinks it has no submissions, as shown in the second screen shot.  This persists after caches have been cleared twice.

The problem started when a new submission was uploaded 12/21. The new submission can be parsed by Protege (I'm told), but has two root concepts so does not do well as a SKOS file. d

All the submissions (including the latest one #6, that did not parse successfully) are shown in http://data.bioontology.org/ontologies/FDC-GDMT/submissions.

Trying to download the 12/21 SKOS file gives 

```
{
-"errors": [
"There is no such submission for download"
],
"status": 404
}
```

All the other submissions download fine. 

![Screen Shot 2020-12-23 at 4.26.00 PM.png](https://images.zenhubusercontent.com/5cc9bdc26c1fd80bacaab82a/a9550169-3ae0-4fd0-9d09-1d346ab30c91)

![Screen Shot 2020-12-23 at 3.48.32 PM.png](https://images.zenhubusercontent.com/5cc9bdc26c1fd80bacaab82a/7e0b086c-f6d1-4a06-bbe2-1d5e15710187)

**Comment by graybeal** [comment]
Troubleshooting on ncboprod-rest1:

```
[jbgmeta1@ncbo-prd-app-14 FDC-GDMT]$ ls -l 5
total 1476
-rw-------. 1 ncbo-deployer ncbo-deployer 294260 Dec 13 23:53 dataset-voc.ttl
-rw-rw-rw-. 1 ncbo-deployer ncbo-deployer  39573 Dec 13 23:53 FDC-GDMT.csv.gz
-rw-rw-rw-. 1 ncbo-deployer ncbo-deployer    601 Dec 13 23:53 labels.ttl
-rw-rw-rw-. 1 ncbo-deployer ncbo-deployer 351861 Dec 13 23:53 mappings.ttl
-rw-rw-rw-. 1 ncbo-deployer ncbo-deployer     54 Dec 13 23:54 metrics.csv
-rw-rw-rw-. 1 ncbo-deployer ncbo-deployer 783492 Dec 13 23:53 owlapi.xrdf
-rw-rw-rw-. 1 ncbo-deployer ncbo-deployer  15066 Dec 14 01:12 parsing.log
[jbgmeta1@ncbo-prd-app-14 FDC-GDMT]$ ls -l 6
total 1064
-rw-------. 1 ncbo-deployer ncbo-deployer 293749 Dec 21 18:04 dataset-voc.ttl
-rw-rw-rw-. 1 ncbo-deployer ncbo-deployer     56 Dec 21 18:04 metrics.csv
-rw-rw-rw-. 1 ncbo-deployer ncbo-deployer 780005 Dec 21 18:04 owlapi.xrdf
-rw-rw-rw-. 1 ncbo-deployer ncbo-deployer    300 Dec 21 22:19 parsing.log
[jbgmeta1@ncbo-prd-app-14 FDC-GDMT]$ more 6/parsing.log
# Logfile created on 2020-12-21 22:19:45 -0800 by logger.rb/v1.4.2
I, [2020-12-21T22:19:45.562162 #17692]  INFO -- : ["Starting to process http://data.b
ioontology.org/ontologies/FDC-GDMT/submissions/6"]
I, [2020-12-21T22:19:45.585886 #17692]  INFO -- : ["Starting to process FDC-GDMT/subm
issions/6"]
```

**Comment by graybeal** [comment]
It would be OK to delete submission 6, but I can't do it via the Admin UI.

**Comment by jvendetti** [comment]
This appears to be another occurrence of the long standing 4store issue where a submission object is written to the triplestore with an invalid data type for the submission ID. Examining the submission object from an ncbo_cron console session on the production parsing box reveals the error:

```
> pry(main)> sub.valid?
=> false
> pry(main)> sub.errors
=> {:submissionId=>{:integer=>"Attribute `submissionId` value `6` must be a `Integer`"}}
```

I deleted the corrupt/orphaned object and recreated submission 6, which is fully available now in BioPortal.

**Comment by jvendetti** [comment]
All of the submissions for this ontology are now visible in the Admin page:

<img width="1637" alt="Screen Shot 2021-01-04 at 12 59 56 PM" src="https://user-images.githubusercontent.com/1696923/103579331-f94ea180-4e8c-11eb-8ca6-bbfd35d7871e.png">

The text in the "ISSUES" column won't be updated until tomorrow (after the nightly ontologies report is generated).
