### ISSUE TITLE
Roots endpoint returns empty set for PANET ontology

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#205]
End user reported on the support list that they're unable to view the class tree for the [PANET ontology](https://bioportal.bioontology.org/ontologies/PANET) in the BioPortal UI. Note that this a private ontology, so you need to be logged in to reproduce.

The underlying cause for the UI issue is that the /roots endpoint is returning an empty set, so the UI can't construct a class tree:

http://data.bioontology.org/ontologies/PANET/classes/roots

I'm noting a couple of things about this ontology that might be worth investigating. If you open it in Protege, there is only one class under owl:Thing with a subject URI of http://purl.obolibrary.org/obo/OBI_0000070. This subject URI differs from the one in the ontology header:

```<owl:Ontology rdf:about="https://www.diamond.ac.uk/"/>```

Also, a lot of the classes are declared using a colon character in rdf:about, e.g.:

```
<owl:Class rdf:about="ExPaNDS:diffraction">
  <rdfs:subClassOf rdf:resource="ExPaNDS:elastic scattering"/>
  <obo:IAO_0000119 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">https://en.wikipedia.org/wiki/Diffraction</obo:IAO_0000119>
  <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">diffraction</rdfs:label>
</owl:Class>
```

If you select such a class in Protege and bring up the "Change Entity IRI" dialog (Refactor -> Rename entity...), the dialog content is blank:

<img width="1113" alt="Screen Shot 2021-02-08 at 12 35 25 PM" src="https://user-images.githubusercontent.com/1696923/107278124-336e0e80-6a0a-11eb-8052-d759f8feb767.png">

I haven't seen this type of behavior in Protege before, and I wonder if there's something about the way this ontology is constructed that causes issues in our system in terms of determining roots classes.

**Comment by graybeal** [comment]
Well, could it be that ExPaNDS is not defined as a prefix anywhere, but seems to be used as one?

**Comment by jvendetti** [comment]
I was thinking about that possibility. I would have expected the OWL API to throw an error about a missing prefix, but perhaps memory isn't serving correctly.

**Comment by graybeal** [comment]
I *think* it's OK (ontologically, anyway) that the Subject defined by the OBI class OBI_0000070 is different than the Ontology rdf:about declaration—I think those are independent declarations with different semantics.

**Comment by graybeal** [comment]
Although Protege isn't reporting any errors, http://visualdataweb.de/validator reports that the first declaration that has the `ExPaNDS:` notation doesn't have a good IRI. Some testing reveals that spaces are bad in IRI strings, at least as far as that validator is concerned.

**Comment by jvendetti** [comment]
This ontology is properly displaying in BioPortal now. I haven't looked at this issue since last year. I don't remember what was done to address the issue.
