### ISSUE TITLE
BIBLIOTEK-O: failure to create new submissions from pull URL

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#21]
User reported that a new version of the [BIBLIOTEK-O](http://bioportal.bioontology.org/ontologies/BIBLIOTEK-O) ontology was uploaded to their pull URL location on May 5th, but BioPortal doesn't reflect any new submissions.  The UI is only showing one submission from April 27th.

I verified that the pull URL is valid.  The ncbo_cron log file (scheduler-pull.log-20170503) shows the following error:

```
I, [2017-05-06T18:00:13.692998 #2933]  INFO -- : Checking download for BIBLIOTEK-O
I, [2017-05-06T18:00:13.693093 #2933]  INFO -- : Location: http://bibliotek-o.org/ontology.owl
I, [2017-05-06T18:00:14.298737 #2933]  INFO -- : New file found for BIBLIOTEK-O
old: 7ffc552d7c5232786c2edab87254a6f4
new: 71fb90b20e00f28c42b0a7aa2bd42bf2
E, [2017-05-06T18:00:14.367743 #2933] ERROR -- : Unable to create a new submission in OntologyPull: {:proc_naming=>{:duplicate=>"There is already a persistent resource with id `http://data.bioontology.org/ontologies/BIBLIOTEK-O/submissions/2`"}}
```

**Comment by jvendetti** [comment]
Submission 2 of this ontology isn't accessible via our REST API, i.e., the following call only returns the initial submission with ID of 1: http://data.bioontology.org/ontologies/BIBLIOTEK-O/submissions.

I executed the following query against the production triplestore:

```
SELECT DISTINCT ?id ?submissionId 
FROM <http://data.bioontology.org/metadata/OntologySubmission> 
WHERE { ?id a <http://data.bioontology.org/metadata/OntologySubmission> . OPTIONAL { ?id <http://data.bioontology.org/metadata/submissionId> ?submissionId . } FILTER(?id = <http://data.bioontology.org/ontologies/BIBLIOTEK-O/submissions/2>) }
```

... which shows that a triple exists with a submission ID of 2:

```
<?xml version="1.0"?>
<sparql xmlns="http://www.w3.org/2005/sparql-results#">
  <head>
    <variable name="id"/>
    <variable name="submissionId"/>
  </head>
  <results>
    <result>
      <binding name="id"><uri>http://data.bioontology.org/ontologies/BIBLIOTEK-O/submissions/2</uri></binding>
      <binding name="submissionId"><literal datatype="http://www.w3.org/2001/XMLSchema#integer">2</literal></binding>
    </result>
  </results>
</sparql>
```

It's unclear how the system ends up in this state with a triple that's orphaned from the API.  See also #4.

**Comment by mdorf** [comment]
Documented necessary deletion command in Github internal documentation pages.

**Comment by graybeal** [comment]
delete_orphan_records_from_triple_store.txt
