### ISSUE TITLE
ECSO ontology not displaying classes/properties

### ISSUE THREAD

**Issue by graybeal** [ncbo/bioportal-project#223]
The ECSO ontology is showing errors instead of data for the classes and properties tab, shows that metrics haven't been calculated even though the log file seems to say they have, and https://data.bioontology.org/ontologies/ECSO/classes
produces 
```
{
-"errors": [
"Ontology 'ECSO' not found."
],
"status": 404
}
```

Seems like to be a metadata error.

**Comment by mdorf** [comment]
I am unable to reproduce this issue. A clear of the internal caches may have fixed it.
