### ISSUE TITLE
process and load UMLS 2021AB release

### ISSUE THREAD

**Issue by alexskr** [ncbo/bioportal-project#228]

**Comment by alexskr** [comment]
NCBITAXON ontology hasn't been updated since 2020AB and needs to be fixed

**Comment by alexskr** [comment]
owlapi-wrapper run out of java heap space.  Hardcoded `-Xmx10240M` is not enough to process NCBITAXON

**Comment by jonquet** [comment]
Hi @alexskr 
@syphax-bouazzouni has created a PR to address the setting of the heap-size: 
https://github.com/ncbo/ontologies_linked_data/pull/130

We have another out of memory issue showing up (at 4store level) after significantly increasing the heap size at the owl-api level (10>20Gb). We would be interested to know if you run into this too with NCBITAXON. 
https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/15#issuecomment-1055388402

**Comment by alexskr** [comment]
@syphax-bouazzouni PR looks great!  Thank you!

@jonquet we are not running into this particular problem with 4store when processing NCBITAXON but our environment might be different from what you have.  We use separate/dedicated VMs for parsing/ncbo_corn and for 4store so we don't have a memory contention issue you might be running into.   Also, we use a secondary 4store instance when processing UMLS ontologies so that it doesn't have to serve life bioportal traffic.
