### ISSUE TITLE
UATC purls wrong

### ISSUE THREAD

**Issue by graybeal** [ncbo/bioportal-project#231]
User comments (and I've confirmed):
```
All PURLs for ATC (https://bioportal.bioontology.org/ontologies/ATC/) appear to be incorrect - they contain the acronym "UATC" instead of "ATC" and consequently do not resolve to the correct records. 
```

**Comment by alexskr** [comment]
@graybeal There are two ways to fix this issue:
1. update uml2rdf config file and re-generate ACT with `http://purl.bioontology.org/ontology/ATC` PURL prefix. 
2. do not change the PURL but set up redirection on the purl server such that  `http://purl.bioontology.org/ontology/UATC`  gets redirected to  `http://bioportal.bioontology.org/ontology/ATC` 

In the past, we have done solution `#2` for ontologies like WHO-ART, AI-RHEUM,COSTART, and solution `#1` for SNOMEDCT, MEDDRA, etc.

my vote is for the first solution which is more straight forward but it might introduce inconsistencies for users who rely on the current PURL prefix

**Comment by graybeal** [comment]
Yes, I vote for the first solution, especially as we're about to regenerate it anyway. If we get complaints the second is an option, at least for a time. But someone will want UATC eventually so hopefully we can drop it now.

**Comment by alexskr** [comment]
done

**Comment by alexskr** [comment]
re-processed ATC ontology with updated PURL

**Comment by piehld** [comment]
Hello, thank you for resolving this issue. I can see this update reflected in the CSV file that's available for download. However, it appears that the "Parents" field is missing for a handful of classes which previously had a Parent. Specifically, here are the few that I noticed:
```
http://purl.bioontology.org/ontology/ATC/J05AJ03
http://purl.bioontology.org/ontology/ATC/R05CA02
http://purl.bioontology.org/ontology/ATC/N02BA59
http://purl.bioontology.org/ontology/ATC/R06AA04
http://purl.bioontology.org/ontology/ATC/C02BC
http://purl.bioontology.org/ontology/ATC/B01AX07
http://purl.bioontology.org/ontology/ATC/A06AG20
http://purl.bioontology.org/ontology/ATC/J05AE
http://purl.bioontology.org/ontology/ATC/C01BD06
http://purl.bioontology.org/ontology/ATC/J06AA02
```

**Comment by jvendetti** [comment]
@piehld - I've entered a new issue (#249) regarding the empty Parents fields

**Comment by piehld** [comment]
@jvendetti Thank you very much
