### ISSUE TITLE
BioPortal U24: provide 4store dump to Lawrence Berkeley National Laboratory

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#236]
@alexskr - the BioPortal U24 grant has kicked off, and we'd like to provide our collaborators at LBNL with a dump of our production 4store data. 

Do I remember correctly that you've created dumps before? If so, are you able to provide a dump minus the private ontologies?

Also, are you able to clarify the format of the dumps? Is it RDF triples?

**Comment by nlharris** [comment]
I can't tag Chris or me or add labels or anything to this ticket. When @graybeal has a chance maybe he can give me more powers in the ncbo org.

**Comment by jvendetti** [comment]
@nlharris - I sent an invitation to give you "triage" access. Does that help?

**Comment by nlharris** [comment]
Yes! Thanks!

**Comment by nlharris** [comment]
Can you give cmungall a level that lets us @ him?

**Comment by alexskr** [comment]
4store dump/export creates an N-Triples file for each graph but we could covert that to n-quad as a single file if that's better.

**Comment by jvendetti** [comment]
@nlharris - I sent Chris an invitation with the same "triage" privileges. Let me know once he accepts if you're able to @ him.

**Comment by nlharris** [comment]
Thanks! Not yet, but he may not have responded to the invitation yet.

**Comment by alexskr** [comment]
I uploaded 4store data dump of public ontologies to the google drive
