### ISSUE TITLE
Remove Resource Index dependency across BioPortal API layer

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#237]
The [NCBO Resouce Index](https://github.com/ncbo/resource_index) is deprecated / hasn't been under active development for years. Most of BioPortal's API layer repositories still have a dependency on the Resource Index, including: 

- ontologies_api
- ontologies_linked_data
- ncbo_ontology_recommender
- ncbo_annotator
- ncbo_cron

The Resource Index code base has very old dependencies, e.g., Elasticsearch 2.0.0 from Oct., 2015. This is making it increasingly difficult to keep other dependencies in our API layer up to date. For example, I recently had to pin the faraday gem to 1.9 across the API layer. Moving to the 2.x series causes exceptions from the Resource Index code base, and all unit tests suites immediately fail.

**Comment by jvendetti** [comment]
Ideally after the dependency is removed, we could use GitHub's [repository archiving functionality](https://github.blog/2017-11-08-archiving-repositories/) to mark the Resource Index as archived (still accessible to everyone, but read-only).

**Comment by alexskr** [comment]
resolved in https://github.com/ncbo/ontologies_api/releases/tag/v5.23.0
