### ISSUE TITLE
Incorrect character display for terms in Spanish language SNOMED

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#238]
End user reported on the support list that there are display issues with the character set for Spanish language version of SNOMEDCT ([SCTSPA](https://bioportal.bioontology.org/ontologies/SCTSPA?p=classes)).

One example is the class with a CUI of C0586399. The issue is visible both at the UI layer:

https://bioportal.bioontology.org/ontologies/SCTSPA/?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FSCTSPA%2F308916002

... and at the REST layer:

http://data.bioontology.org/ontologies/SCTSPA/classes/http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FSCTSPA%2F308916002?display_links=false&display_context=false

Screen shot:

![Screen Shot 2022-02-03 at 5 44 25 PM](https://user-images.githubusercontent.com/1696923/152458741-3b993b0f-b05a-43cb-8113-b5b72e05cb0b.png)

You can view the same term in the UMLS Metathesaurus browser: https://uts.nlm.nih.gov/uts/umls/concept/C0586399. Using their site, the a and o acute characters are properly displayed: "ambiente o localización geográfica".

**Comment by alexskr** [comment]
fixed, relates to https://github.com/ncbo/umls2rdf/issues/45
