### ISSUE TITLE
CHEAR: latest submission failed to parse

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#24]
The latest submission of the [CHEAR ontology](http://bioportal.bioontology.org/ontologies/CHEAR) failed to parse (status shows "Error Rdf") in the BioPortal UI.

Parsing logs indicate that the ontology was successfully parsed by the OWL API, but failed the secondary rapper parsing step:

```
I, [2017-05-23T07:57:20.760933 #3345]  INFO -- : ["OWLAPI Java command: parsing finished successfully."]
I, [2017-05-23T07:57:20.761117 #3345]  INFO -- : ["Output size 11890550 in `/srv/ncbo/repository/CHEAR/3/owlapi.xrdf`"]
E, [2017-05-23T07:57:21.540084 #3345] ERROR -- : ["Exception: Rapper cannot parse rdfxml file at /srv/ncbo/repository/CHEAR/3/owlapi.xrdf: 
rapper: Parsing URI file:///srv/ncbo/repository/CHEAR/3/owlapi.xrdf with parser rdfxml
rapper: Serializing with serializer ntriples
rapper: Error - URI file:///srv/ncbo/repository/CHEAR/3/owlapi.xrdf:169752 - Illegal rdf:nodeID value '_:genid8154'
```

Manually running rapper command confirms that rapper is unable to serialize the content in the owlapi.xrdf file:

```
[ncbo-deployer@ncbo-prd-app-25 3]$ rapper -i rdfxml -o ntriples owlapi.xrdf > data.triples
rapper: Parsing URI file:///srv/ncbo/share/env/production/repository/CHEAR/3/owlapi.xrdf with parser rdfxml
rapper: Serializing with serializer ntriples
rapper: Error - URI file:///srv/ncbo/share/env/production/repository/CHEAR/3/owlapi.xrdf:169752 - Illegal rdf:nodeID value '_:genid8154'
rapper: Failed to parse file owlapi.xrdf rdfxml content
rapper: Parsing returned 104863 triples
```

**Comment by jvendetti** [comment]
This ontology has 7 individuals with object property assertions that appear to have invalid individual names as the value.  The individuals in question are:

AmericanIndianOrAlaskanNative
Asian
BlackOrAfricanAmerican
HispanicOrLatino
NativeHawaiianOrOtherPacificIslander
NonHispanicOrLatino
White

The object property is "is described by".  Protege will load this ontology file without errors, but will display an error message if the user attempts to edit any of these object property assertions.

![screenshot 2017-05-23 17 01 45](https://cloud.githubusercontent.com/assets/1696923/26381977/8f0ab7bc-3fdd-11e7-8bf8-080534be83b1.png)

Not positive, but I suspect the blank node identifiers (rdf:nodeID) in the declarations of these individuals are giving the parsers problems.  See the following snippet from the ontology file:

```
<!-- http://hadatac.org/ont/chear/AmericanIndianOrAlaskanNative -->

<owl:NamedIndividual rdf:about="http://hadatac.org/ont/chear/AmericanIndianOrAlaskanNative">
    <sio:isDescribedBy>
        <rdf:Description rdf:nodeID="_:genid130">
            <rdf:type rdf:resource="http://semanticscience.org/resource/Definition"/>
            <prov:wasAttributedTo rdf:resource="http://hadatac.org/kb/chear#PER-Jeanette-Stingone"/>
            <prov:wasQuotedFrom rdf:resource="https://www.whitehouse.gov/sites/default/files/omb/assets/information_and_regulatory_affairs/re_app-a-update.pdf"/>
            <sio:hasValue>A person having origins in any of the original peoples of North, Central, or South America, and who maintains tribal affiliations or community attachment.</sio:hasValue>
        </rdf:Description>
    </sio:isDescribedBy>
    <skos:definition>A person having origins in any of the original peoples of North, Central, or South America, and who maintains tribal affiliations or community attachment.</skos:definition>
</owl:NamedIndividual>
```

**Comment by graybeal** [comment]
If the nodeId is an IRI (or URI?), colons aren't legal. Had that problem with the DMTO ontology recently.

**Comment by jvendetti** [comment]
Ontology author fixed the object property assertions and resubmitted. CHEAR is now parsed and available for browsing, etc.
