### ISSUE TITLE
process and load UMLS 2022AA release

### ISSUE THREAD

**Issue by alexskr** [ncbo/bioportal-project#245]
UMLS 2022AA release is out as of May 2nd.

**Comment by jvendetti** [comment]
@graybeal mentions that there are important workshops coming up on June 20th and 23rd. As a result, initial estimate for beginning the import process is the weekend of June 25th/26th.

**Comment by jvendetti** [comment]
Latest schedule:

> UMLS load will happen July 1-4th + a few days to finish rebuilding search index and annotator cache

**Comment by alexskr** [comment]
UMLS 2022AA is loaded
