### ISSUE TITLE
Copy current (private) docker_compose.yml file to public repo

### ISSUE THREAD

**Issue by graybeal** [ncbo/bioportal-project#267]
Make a copy of the currently private 'development' docker_compose.yml file available in a public repository.

Name it to make clear it is not the best version.

Make sure the README file for that directory makes clear we are not providing support for this software, that it is informational only.

**Comment by graybeal** [comment]
differences in private repo include:
* Private repo works on assumption that unit test is working on desktop (via cmd line); public repo assumes dev and unit testing are in container
* private repo is local code running on Mac with all dependencies; public repo is code running inside docker container
* For public repo, will need to docker-related GitHub repo to keep track of dependency configuration
    * for instance mgrep container built by Alex and published, not have to be built from scratch
    * repo for managing servers has to be built
* Public repo needs config stuff to make ports open
* Public repo needs time to polish it and make it available
* Public repo only addresses the API development
* Better to use the public repo as the basis of further development (a unified docker_compose file) 
   * can use it to run the whole API stack
   * can add the UI component to that

**Comment by alexskr** [comment]
docker-compose file is copied to https://github.com/ncbo/ontoportal_utilities/blob/master/docker/docker-compose.dev.yml
ontoportal_utilities is a collection of various scripts and tools but this repo is not the final place for docker-compose files
