### ISSUE TITLE
Ruby v3.0 support

### ISSUE THREAD

**Issue by alexskr** [ncbo/bioportal-project#275]
BP/Ontoportal is currently working with ruby v2.7 which is in its maintenance phase and will be EOL soon.
We should start adopting ruby v3.0

So far only ontologies_api_ruby_client project is running unit tests against ruby v3.0

**Comment by jvendetti** [comment]
BioPortal Rails application is on Ruby 3 as of mid September

See this release: https://github.com/ncbo/bioportal_web_ui/releases/tag/v6.13.0

**Comment by jvendetti** [comment]
Currently there are [three stable Ruby releases](https://www.ruby-lang.org/en/downloads/) available for download (3.1.4, 3.2.2, and 3.3.0). What version does everyone think we should target for the REST API?

**Comment by alexskr** [comment]
Currently ontologies_api doesn't work with ruby 3.0+  Throttling unit tests do not pass.   We should move to latest version of ruby that API can run on.

**Comment by jvendetti** [comment]
I'm aware that it doesn't work with Ruby 3.0+. I asked about this because I'm interested to know what version we should be targeting when we start working on fixing the code to be compatible.

**Comment by syphax-bouazzouni** [comment]
Everyone seems to say that 3.3.0 is a game-changer in [terms of performance ](https://railsatscale.com/2023-12-04-ruby-3-3-s-yjit-faster-while-using-less-memory/)
![image](https://github.com/ncbo/bioportal-project/assets/29259906/0e29d4f9-d5f5-487c-8a39-9c7d5a188abd)

**Comment by alexskr** [comment]
It would be great to use the same ruby version for both API and UI.

**Comment by syphax-bouazzouni** [comment]
![image](https://github.com/ncbo/bioportal-project/assets/29259906/c3ece0a7-065d-420b-b97d-aa1a9614f611)

**Comment by alexskr** [comment]
related PR:
https://github.com/ncbo/ontologies_api/pull/159
https://github.com/ncbo/ontologies_linked_data/pull/214
https://github.com/ncbo/ncbo_annotator/pull/34

**Comment by alexskr** [comment]
done
