### ISSUE TITLE
unnecessary system load generated by the persistent redis instance

### ISSUE THREAD

**Issue by alexskr** [ncbo/bioportal-project#280]
currently, we use persistent redis instances to hold the following:
* annotator cache
* dictionary rebuild time stamp (needed for triggering mgrep restarts)
* ncbo_cron job queue
* google analytics data
* appliance uuid

Currently, redis is configured to persist data to disk with `save 300 10` which means save to disk every 5 minutes if 10 keys were changed which is what we are observing.  Persisting the annotator cache every 5 minutes even when no new ontologies are processed is less than ideal because it creates unnecessary high CPU/DISK/RAM usage.

<img width="690" alt="Pasted Graphic 5" src="https://user-images.githubusercontent.com/1591816/230993040-b21b7321-6a96-4034-87e8-f7b9b48df70f.png">

My guess is that  ncbo_cron job scheduler uses a locking mechanism for checking job queue, resulting in at least 10 writes / 5 minutes.

**Comment by syphax-bouazzouni** [comment]
> My guess is that ncbo_cron job scheduler uses a locking mechanism for checking job queue, resulting in at least 10 writes / 5 minutes.

Maybe the cause is this [job](https://github.com/ncbo/ncbo_cron/blob/master/bin/ncbo_cron#L249C4-L249C4) scheduled each [5minutes ](https://github.com/ncbo/ncbo_cron/blob/master/lib/ncbo_cron/scheduler.rb#L39)

This job calls the function [queued_items](https://github.com/ncbo/ncbo_cron/blob/master/lib/ncbo_cron/ontology_submission_parser.rb#L40) which does the calls to Redis.

**Comment by alexskr** [comment]
yes, that is exactly what was the issue.  We deployed 4th instance of redis and dedicated it to `ncbo_cron.config.redis_host` and  `LinkedData.config.ontology_analytics_redis_host` which alleviated this issue.   
I don't think this would be a significant issue for ontoportals with small number of ontologies.
@syphax-bouazzouni are you experiencing this issue in your environment?

**Comment by syphax-bouazzouni** [comment]
> @syphax-bouazzouni are you experiencing this issue in your environment?

No, not really just pass over this issue and became intrigued by it.
