### ISSUE TITLE
Virtual Appliance's Recommender's ontology links bad

### ISSUE THREAD

**Issue by graybeal** [ncbo/bioportal-project#29]
See https://github.com/ESIPFed/Semantic-Portal/issues/8 for original report. The linked ontologies in the list of Recommended ontologies don't resolve, because there's an extra http:// in the URL. 
I suspect this is do to a configured attribute, but it might be a bug. Do we know?

**Comment by linepouchard** [comment]
The install causing this problem is located here:
[http://semanticportal.esipfed.org](url)

**Comment by alexskr** [comment]
There appears to be an issue how links are rendered on the recommender page even in the current version of bioportal.  For example, https version of the bioportal site renders links as http instead of the https.  Annotator page doesn’t have this issue which makes me think that its not exactly a configuration issue but a problem with the recommender page.

**Comment by jvendetti** [comment]
The difference between the results tables on the Annotator and Recommender pages is that the Annotator results table is constructed with *relative* URLs to ontologies and classes. I found some JavaScript code that converts URLs returned from the REST API from full URLs to relative URLs before the Annotator results table is constructed. We should augment the code for the Recommender page to do the same.

**Comment by linepouchard** [comment]
Thanks, Jennifer. 
Line

Sent from my iPhone
Line Pouchard
Brookhaven National Lab

**Comment by jvendetti** [comment]
Modified the Recommender page to use relative URLs in the following two commits:

https://github.com/ncbo/bioportal_web_ui/commit/9b80a092e60d50b7d39b851319a3c0316175f858
https://github.com/ncbo/bioportal_web_ui/commit/6aff4d7bfdf2eb73fb2d07d1be5976e96972c577

@alexskr - are you able to test if the links are working now in our VA instance?
