### ISSUE TITLE
Retire the open SPARQL endpoint

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#290]
We still get asked on occasion about the BioPortal open SPARQL endpoint, e.g. https://mailman.stanford.edu/pipermail/bioontology-support/2023-November/013309.html.

It contains ontology data at least 10 years out-of-date, and of late has become inaccessible. The BioPortal development team has Mark's blessing to retire this functionality (see Oct. 13th [meeting notes](https://docs.google.com/document/d/1H1oQDY5JREzcDnsoNjCaxTVPCuNn4UN8iAaCS0K5OcY/edit#heading=h.7di56hlv11cw)).

## Tasks

- [x] Update [documentation](https://www.bioontology.org/wiki/SPARQL_BioPortal) on the NCBO Wiki to indicate deprecation of the endpoint
- [x] Set up redirect of sparql.bioontology.org to the documentation/retirement notice

**Comment by jvendetti** [comment]
@alexskr - I added a deprecation / shut down notice at the top of the wiki page that describes the open SPARQL endpoint. I think we're ready for the other task now of setting up a redirect.

**Comment by alexskr** [comment]
redirect is in place
