### ISSUE TITLE
Remove broken/test ontology GFDHFGHDFGH

### ISSUE THREAD

**Issue by caufieldjh** [ncbo/bioportal-project#301]
See https://bioportal.bioontology.org/ontologies/GFDHFGHDFGH/

**Comment by jvendetti** [comment]
Created by account name `ran-codes`.

Deleted GFDHFGHDFGH, as well as several other ontology entries created by this user that were either test ontologies or ontologies with no submissions - everything in the list in the screenshot below except for UHC-METADATA.

<img width="324" alt="Screenshot 2024-02-12 at 4 06 04 PM" src="https://github.com/ncbo/bioportal-project/assets/1696923/f673d11d-dfbe-4469-a1a5-c2ce8d6e6bd8">
