### ISSUE TITLE
Add ontology language

### ISSUE THREAD

**Issue by caufieldjh** [ncbo/bioportal-project#304]
A sub-issue of #296.

I have curated language tags for all Bioportal ontologies as of today (Feb 12 2024) - just need a place to include them in each ontology entry.

Out of 1107 ontologies (may be a few duplicates in there):
1092 are in English (but some are bilingual),
11 in French,
5 in Chinese,
3 in Japanese,
3 in Spanish,
2 in Persian,
and 1 in German.

**Comment by jvendetti** [comment]
@jonquet and/or @syphax-bouazzouni - do I understand correctly that in AgroPortal you chose to store ontology language in the [naturalLanguage](https://github.com/ontoportal-lirmm/ontologies_linked_data/blob/95e77989e4e8ea2fde86cf4f048f7d6cd7a6829f/lib/ontologies_linked_data/models/ontology_submission.rb#L56) metadata attribute?

**Comment by syphax-bouazzouni** [comment]
> @jonquet and/or @syphax-bouazzouni - do I understand correctly that in AgroPortal you chose to store ontology language in the [naturalLanguage](https://github.com/ontoportal-lirmm/ontologies_linked_data/blob/95e77989e4e8ea2fde86cf4f048f7d6cd7a6829f/lib/ontologies_linked_data/models/ontology_submission.rb#L56) metadata attribute?

Yes, exactly, you can see the values here: https://data.agroportal.lirmm.fr/submissions?display=naturalLanguage&disaply_links=false&display_context=false&apikey=1de0a270-29c5-4dda-b043-7c3580628cd5

**Comment by jvendetti** [comment]
Thank you @syphax-bouazzouni , though I'm wondering why this attribute was chosen instead of using the [hasRepresentationLanguage](https://www.isibang.ac.in/ns/mod/2.0/index-en.html#hasRepresentationLanguage) attribute from [MOD](https://github.com/FAIR-IMPACT/MOD)?

**Comment by jonquet** [comment]
Hello @jvendetti 
A bit of history first: 
We have build MOD (then v1.4) and AgroPortal metadata model in parallel in 2017. Every time a property would be already there in BioPortal, we did not change it to stay backward compatible. And we pushed MOD 1.4 to rely has much as we can on OMV as BioPortla did in the past. 
Later in MOD2, we decided (with a larger group of people, and envisaging a better commitment and engagement of communities, RDA, EOSC, OntoPortal, etc..)that the properties from OMV will be dropped and readopted within the MOD namespace and sometime rename slightly (to represent the fact that MOD is not only for ontologies but for semantic artefact in general).

So, to encode the natural language of the ontology, OMV originally proposed omv:naturalLanguage property (OMV def: The language of the content of the ontology, i.e. English, French, etc.). This is still the one we use today. 

Note that OMV also proposed omv:hasOntologyLanguage property (OMD def: OMV: The ontology language) which was already there in BioPortal to encode the "format" (I don't really like this word and OMV did not too and used 2 properties: one for the representation language and one for the syntax.. but BioPortal used only one at Natasha's time). 
Later in 2020,  omv:hasOntologyLanguage was adopted by MOD2 and changed to mod:hasRepresentationLanguage. So this property is still the one we recommend to use (MOD def: MOD: A representation language that is used to create an ontology (e.g., OWL, RDF-S, SKOS).) ... even if BioPortal/AgroPortal does still use the old one. 

(I will reply on the notion of "compliance with MOD" in your other issuehttps://github.com/ncbo/ontologies_linked_data/issues/192)

**Comment by jvendetti** [comment]
OK, thank you @jonquet for the historical perspective. This clears things up for me. I suppose for the sake of expediency, we should proceed with storing the language tags that @caufieldjh curated in the [naturalLanguage attribute](https://github.com/ncbo/ontologies_linked_data/blob/0003905c5d101f4df17e35784c0d15d2f5d42110/lib/ontologies_linked_data/models/ontology_submission.rb#L36) on the OntologySubmission class. My presumption is that we'd need to do that programmatically on the latest "ready" submission object for each ontology.

A possible issue with this attribute sticking - we don't expose a way in the Rails application for users to choose the natural language of their ontology when they manually create new submissions.

**Comment by jonquet** [comment]
Indeed, this is a property we added to the submission model. 
For your second point, indeed if you add a property, there needs to be an addition in the form for this... 

The UI developped in https://github.com/ontoportal-lirmm/bioportal_web_ui (untill v2.4) shall be useful: 
<img width="994" alt="Capture d’écran 2024-02-22 à 14 06 59" src="https://github.com/ncbo/bioportal-project/assets/7379183/fdbb9f84-3cb6-4d7f-bc5d-001429bff00a">

Note that we don't recommend iso639-3 any more (too much values, no one use them)... we do recommend (and rely in the multilingual support code on iso639-1 values ... still from Lexvo.

**Comment by jvendetti** [comment]
@caufieldjh - all of the necessary modifications have been implemented / released to production to accommodate addition of the language tags that you curated. I think it would be easiest for me to do this programmatically on my end since you need to have admin privileges on ontologies in order to edit their latest submissions. Is this agreeable to you?

**Comment by caufieldjh** [comment]
Sure, I think that should be OK.
