### ISSUE TITLE
Need to update contact person on About page

### ISSUE THREAD

**Issue by nlharris** [ncbo/bioportal-project#324]
https://www.bioontology.org/about-us/ lists John Graybeal as the contact person for Outreach & Software Demos. I thought I could find that page here and do a PR to fix it but it's not here. I think maybe it's a wiki page but I didn't see a way to edit it.

**Comment by jvendetti** [comment]
bioontology.org is (unfortunately) a WordPress site.

@alexskr - I tried logging into the site, but get a "Your access to this site has been temporarily limited by the site owner" message. I went through the process of requesting the unlock email - I get a message, but clicking on the link to reinstate access had no effect. Can you have a look at this?

<img width="964" alt="Screenshot 2024-09-25 at 8 46 14 AM" src="https://github.com/user-attachments/assets/86428970-709b-4ab2-b047-c9ab51488a1b">

**Comment by jvendetti** [comment]
@alexskr - Mark asked us to set up a dedicated email address for outreach / software demos. I'm wondering if you could do that when you have time? I can update the WordPress site when we have the new email.

**Comment by alexskr** [comment]
I can create `info@` `demos@` or `outreach@bioontology` forwarding email address any preference?

**Comment by jvendetti** [comment]
Out of what you suggested I like `info@`

**Comment by alexskr** [comment]
email address `info@bioontology` is created
