### ISSUE TITLE
Search for "HPO" doesn't find it

### ISSUE THREAD

**Issue by nlharris** [ncbo/bioportal-project#336]
I tried searching for HPO and was puzzled not to find it. It turns out it’s listed as HP (https://bioportal.bioontology.org/ontologies/HP). I think HP is used as the term prefix, but HPO is definitely referred to (widely) as HPO. Is there a way to add that as a synonym for the ontology name? (More generally, a way to add synonyms for the ontology name or identifier would be a nice feature.)

@alexskr noted:
> BioPortal doesn't have a notion of alternate acronyms for an ontology so a remediation would be to rename HP to HPO ontology while leaving a summary only ontology with a note that that ontology is renamed.  BioPortal doesn't have a mechanism to change acronyms of ontologies but theoretically should be possible if we manipulate things on the backend.

**Comment by jvendetti** [comment]
The HPO acronym is already taken in BioPortal by the "Hypertension-Ontology" (https://bioportal.bioontology.org/ontologies/HPO).

I poked around the MOD standard website (https://github.com/FAIR-IMPACT/MOD), but I don't see any kind of metadata property that's used for housing synonyms for ontology names or identifiers. That said, I couldn't find any human readable documentation of the MOD standard, so it's possible I'm missing something.

**Comment by nlharris** [comment]
I'm pretty sure that when HPO is mentioned, most people think of the Human Phenotype Ontology. On BP, HP has 401 visits in Nov 2024; Hypertension Ontology has 3.

On obofoundry, Hypertension Ontology is https://obofoundry.org/ontology/htn.html

However, I noticed that Human Phenotype Ontology on obofoundry is https://obofoundry.org/ontology/hp.html, and searching for HPO doesn't find it. So it's not that BioPortal is wrong for listing HPO as HP.

I will mention this issue to the HPO people and they can pursue it if they want to.

**Comment by nlharris** [comment]
https://github.com/obophenotype/human-phenotype-ontology/issues/10929

**Comment by nlharris** [comment]
I think we can close this issue as "not planned", since it's not actually a bug and it doesn't seem like there's an easy way to enable the addition of synonyms to ontology names.

**Comment by jvendetti** [comment]
I just noticed that the HPO ([Hypertension-Ontology](https://bioportal.bioontology.org/ontologies/HPO)) in BioPortal is declared as a "view" of the HTN ([Hypertension Ontology](https://bioportal.bioontology.org/ontologies/HTN?p=summary)). This seems a bit odd as HTN is an OBO Foundry ontology, and it's not evident to me what the relationship is here - other than something the end user created when they uploaded HPO. I wonder if this is a case where we should do some manual outreach and ask the submitter if they still need this HPO entry? I'll drop them a note and see if I get a response.

**Comment by nlharris** [comment]
Thanks! (And sorry for creating this issue in the wrong repo!)

**Comment by jvendetti** [comment]
I corresponded with the contact person for HPO. They're still actively using this ontology, so freeing up the HPO acronym isn't possible. I did however confirm that HPO isn't a subset of HTN, and went ahead and removed the "view of" association between the two.
