### ISSUE TITLE
UI project pages display problems when projects include private or non-existing ontologies

### ISSUE THREAD

**Issue by alexskr** [ncbo/bioportal-project#35]
Bioportal UI has a couple of projects that result in 500 error:

http://bioportal.bioontology.org/projects/BioPAX
http://bioportal.bioontology.org/projects/Dispedia
http://bioportal.bioontology.org/projects/DwC

BioPAX project includes private ontology which breaks this page. 
DwC project lists non-existing ontology 

rails produce the following error:
```
F, [2017-07-20T16:09:43.042618 #12700] FATAL -- : 
ActionView::Template::Error (undefined method `name' for nil:NilClass):
    25:     %ul
    26:       - for ontology_id in @usedOntologies
    27:         - ontology = LinkedData::Client::Models::Ontology.find(ontology_id)
    28:         %li= link_to ontology.name, ontology_path(ontology.acronym)
  app/views/projects/show.html.haml:28:in `block in _app_views_projects_show_html_haml___2905672383814142838_70044024350080'
  app/views/projects/show.html.haml:26:in `each'
  app/views/projects/show.html.haml:26:in `_app_views_projects_show_html_haml___2905672383814142838_70044024350080'


I, [2017-07-20T16:09:43.043245 #12700]  INFO -- : Processing by ErrorsController#internal_server_error as HTML
I, [2017-07-20T16:09:43.043299 #12700]  INFO -- :   Parameters: {"id"=>"DwC"}
{noformat}
```

**Comment by jvendetti** [comment]
This comment is only in regard to the [DwC project](http://bioportal.bioontology.org/projects/DwC), which referenced a non-existent ontology in it's list of ontologies used.

In the model layer, when an ontology object is deleted, there's [code that removes references](https://github.com/ncbo/ontologies_linked_data/blob/master/lib/ontologies_linked_data/models/ontology.rb#L347) to that ontology for all project objects. This looks like the data corruption we've been seeing where (somehow) incorrect data exists in the triplestore, e.g., ontology objects without required attributes like acronyms or ontology language.

I repaired this object manually in an ncbo_cron console session, so the project description page is now visible again.

**Comment by jvendetti** [comment]
Fixed in this commit: https://github.com/ncbo/bioportal_web_ui/commit/987b41c73d21ed143355df172462bac22cb26e5c.
