### ISSUE TITLE
DCTERMS: classes page displays 404 error

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#40]
User reported on the support list that the [DCTERMS ontology](http://bioportal.bioontology.org/ontologies/DCTERMS) shows as successfully parsed, but navigating to the classes page results in a 404 error.

Underlying error from the UI:

```
Started GET "/ajax/classes/treeview?ontology=DCTERMS&conceptid=root" for ::1 at 2017-08-29 15:55:46 -0700
Processing by ConceptsController#show_tree as */*
  Parameters: {"ontology"=>"DCTERMS", "conceptid"=>"root"}
Missing roots for DCTERMS
  Rendered text template (0.2ms)
Completed 500 Internal Server Error in 47ms (Views: 0.8ms | ActiveRecord: 0.0ms)
```

The REST endpoint [returns an empty set](http://data.bioontology.org/ontologies/DCTERMS/classes/roots) for the root classes.

The problem could potentially be in the owlapi_wrapper project, where classes aren't getting marked as roots during the parsing process. Possible duplicate of the behavior described in #36.

It's worth noting that this submission is an RDF file, which is not one of the formats we officially support.

**Comment by jvendetti** [comment]
I spent some time investigating the ontology sources. When it was uploaded, the format was marked as SKOS. The SKOS namespace is included at the beginning of the file, but the only SKOS construct used is skos:note. There are no skos:concept declarations. 

From the [SKOS primer](https://www.w3.org/TR/skos-primer/#secconcept): "The fundamental element of the SKOS vocabulary is the concept.". Without any skos:concept declarations, this file doesn't quality as a SKOS vocabulary, i.e., there are no terms from which BioPortal could construct a hierarchy.

It appears there was an effort at some point to [represent Dublin Core metadata terms in OWL 2](http://bloody-byte.net/rdf/dc_owl2dl/), but this website hasn't been updated since 2009. If a valid OWL or SKOS representation of the metadata terms can be produced, I'd be happy to attempt a new upload.

**Comment by jonquet** [comment]
DCTERMS is not an ontology and not realy a vocaulbary. It's a set of metadata properties to use to describe any resource. 
The current file is a RDF version of DCTERMS but it's not at all a SKOS vocabulary.

Shall Dublin Core adopt OWL to define DCTERMS then potentially we shall be able to display the properties in the property tab.
