### ISSUE TITLE
BAO: Some classes are missing prefLabel(s)

### ISSUE THREAD

**Issue by mdorf** [ncbo/bioportal-project#52]
BioAssay ontology tree appears to be missing labels for some of the terms:
https://bioportal.bioontology.org/ontologies/BAO/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000105

A further review revealed that some of the classes in the ontology have the prefLabel attribute set to NULL:
http://data.bioontology.org/ontologies/BAO/classes/roots

prefLabel is a required attribute and should not be missing in a any class.

**Comment by chung88** [comment]
Hi Michael, 

https://bioportal.bioontology.org/ontologies/BAO

We uploaded another version of BAO 2.3.3 
![image](https://user-images.githubusercontent.com/3586358/31290017-fa68da04-aa98-11e7-9657-d588448f71c9.png)

I logged into NCBO BioPortal, I see submission two records with BAO 2.3.2 and one with the date 10/04/2017, which should be BAO 2.3.3 date   10/04/2017
![image](https://user-images.githubusercontent.com/3586358/31289948-b965574e-aa98-11e7-8606-96adf9f50312.png)  It makes us think we might have broken something from your side, by uploading the files too close in time, while your routine job could have been running.

Please let us know,

Caty

**Comment by mdorf** [comment]
Hi @chung88, this issue has been fixed. Looks like there was a corrupt data in the submission that you uploaded. I've fixed it and re-processed the ontology. As a byproduct, it looks like the new version of the ontology no longer has empty labels.

**Comment by chung88** [comment]
Thank you!!  It parsed well.

________________________________
