### ISSUE TITLE
DC-CL fails to load

### ISSUE THREAD

**Issue by graybeal** [ncbo/bioportal-project#54]
Get this message:
BioPortal failed to load Dendritic Cell Ontology (DC-CL) from URL: http://obo.cvs.sourceforge.net/*checkout*/obo/obo/ontology/anatomy/cell_type/DC-CL_deployed.obo. 

The ontology status is retired, which explains why it isn't in our list of OBO ontologies that aren't loading. It's a private ontology so no one else will be bothered.

What should we do with these cases?

**Comment by graybeal** [comment]
I clicked on Upload Local File, but without specifying a local file, to stop attempts to upload this location. I copied the URL into the documentation field as a historical note. 

Is that the appropriate ending?

**Comment by jvendetti** [comment]
I think it's been problematic for some time in BioPortal to remove a pull URL from an ontology submission by editing an existing submission. If I look at the submission object you edited in a cron console session, the pull URL still exists:

```
pry(main)> sub = LinkedData::Models::OntologySubmission.where(ontology: [acronym: "DC-CL"], submissionId: 10).first
pry(main)> sub.bring_remaining
pry(main)> sub.pullLocation
=> #<RDF::URI:0x3f943a5d6f5c(http://obo.cvs.sourceforge.net/*checkout*/obo/obo/ontology/anatomy/cell_type/DC-CL_deployed.obo)>
```

And, if you click the "Edit submission information" link in the UI a second time, the change you made didn't stick (even after clearing the caches). Ray Fergerson used to handle issues with pull URLs going defunct, and as I recall, he used to use this process:

1. Download the ontology source file from the last valid submission.
2. Create a new submission.
3. For the new submission, leave all information the same except for choosing the "Upload Local File" option, specifying the source file from step 1.

This is an area of the application that could use improvement, but I don't believe there are any outstanding issues filed as it never made it high enough in the queue for attention.

**Comment by jvendetti** [comment]
New submission created using file upload. Invalid pull URL no longer exists.
