### ISSUE TITLE
problem parsing SWEET

### ISSUE THREAD

**Issue by graybeal** [ncbo/bioportal-project#56]
The SWEET ontology in BioPortal has about 12 classes with the name "error#', where # is a number from 1 to 12 or so. The log reports errors but these do not give a clue what this is or where it is happening (see below).

It's possible this is related to the fact the root ontology (http://sweetontology.net/sweetAll) #includes all the many individual ontologies. But I don't think Protege sees an error.

Any tips?

I, [2017-11-28T21:01:07.008500 #6803]  INFO -- : ["2017-11-28T20:58:33 [main] INFO  o.s.n.o.OntologyParserCommand - Parsing invocation with values: ParserInvocation [inputRepositoryFolder=null, outputRepositoryFolder=/srv/ncbo/repository/SWEET/2, masterFileName=/srv/ncbo/repository/SWEET/2/sweetAll, invocationId=0, parserLog=, userReasoner= true]\n\n2017-11-28T20:58:33 [main] INFO  o.s.ncbo.oapiwrapper.OntologyParser - executor ...\n\n2017-11-28T20:58:34 [main] INFO  o.s.ncbo.oapiwrapper.OntologyParser - Input repository folder is null. Unique file being parsed.\n\n2017-11-28T20:58:58 [main] ERROR o.s.o.r.rdfxml.parser.OWLRDFConsumer - Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error1 for type Class\n\n2017-11-28T20:58:58 [main] ERROR o.s.o.r.rdfxml.parser.OWLRDFConsumer - Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error2 for type Class\n\n2017-11-28T20:58:58 [main] ERROR o.s.o.r.rdfxml.parser.OWLRDFConsumer - Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error3 for type Class\n\n2017-11-28T20:58:58 [main] ERROR o.s.o.r.rdfxml.parser.OWLRDFConsumer - Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error4 for type Class\n\n2017-11-28T20:58:58 [main] ERROR o.s.o.r.rdfxml.parser.OWLRDFConsumer - Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error5 for type Class\n\n2017-11-28T20:59:12 [main] ERROR o.s.o.r.rdfxml.parser.OWLRDFConsumer - Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error6 for type Class\n\n2017-11-28T20:59:12 [main] ERROR o.s.o.r.rdfxml.parser.OWLRDFConsumer - Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error7 for type Class\n\n2017-11-28T20:59:12 [main] ERROR o.s.o.r.rdfxml.parser.OWLRDFConsumer - Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error8 for type Class\n\n2017-11-28T20:59:12 [main] ERROR o.s.o.r.rdfxml.parser.OWLRDFConsumer - Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error9 for type Class\n\n2017-11-28T20:59:12 [main] ERROR o.s.o.r.rdfxml.parser.OWLRDFConsumer - Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error10 for type Class\n\n2017-11-28T20:59:12 [main] ERROR o.s.o.r.rdfxml.parser.OWLRDFConsumer - Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error11 for type Class\n\n2017-11-28T20:59:12 [main] ERROR o.s.o.r.rdfxml.parser.OWLRDFConsumer - Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error12 for type Class\n\n2017-11-28T20:59:13 [main] ERROR o.s.o.r.rdfxml.parser.OWLRDFConsumer - Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error13 for type Class\n\n2017-11-28T20:59:13 [main] ERROR o.s.o.r.rdfxml.parser.OWLRDFConsumer - Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error14 for type Class\n\n2017-11-28T20:59:13 [main] ERROR o.s.o.r.rdfxml.parser.OWLRDFConsumer - Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error15 for type Class\n\n2017-11-28T20:59:13 [main] ERROR o.s.o.r.rdfxml.parser.OWLRDFConsumer - Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error16 for type Class\n\n2017-11-28T21:01:05 [main] INFO  o.s.ncbo.oapiwrapper.OntologyMetrics - Calculating metrics for /srv/ncbo/repository/SWEET/2/sweetAll\n\n2017-11-28T21:01:05 [main] INFO  o.s.ncbo.oapiwrapper.OntologyMetrics - Finished metrics calculation for /srv/ncbo/repository/SWEET/2/sweetAll in 4 milliseconds\n\n2017-11-28T21:01:05 [main] INFO  o.s.ncbo.oapiwrapper.OntologyMetrics - Generated metrics CSV file for /srv/ncbo/repository/SWEET/2/sweetAll\n\n2017-11-28T21:01:05 [main] INFO  o.s.ncbo.oapiwrapper.OntologyParser - Ontology document format: org.semanticweb.owlapi.formats.TurtleDocumentFormat\n\n2017-11-28T21:01:05 [main] INFO  o.s.ncbo.oapiwrapper.OntologyParser - isPrefixOWLOntologyFormat: true\n\n2017-11-28T21:01:05 [main] INFO  o.s.ncbo.oapiwrapper.OntologyParser - isPrefixOWLOntologyFormat: true\n\n2017-11-28T21:01:05 [main] INFO  o.s.ncbo.oapiwrapper.OntologyParser - isPrefixOWLOntologyFormat: true\n\n2017-11-28T21:01:05 [main] INFO  o.s.ncbo.oapiwrapper.OntologyParser - isPrefixOWLOntologyFormat: true\n\n2017-11-28T21:01:05 [main] INFO

**Comment by jvendetti** [comment]
Loading this ontology in Protege results in the same scenario. There are classes in the tree with names like "Error1", "Error2", etc.:

![screenshot 2017-11-30 11 48 45](https://user-images.githubusercontent.com/1696923/33451666-8fb1a02c-d5c4-11e7-8b4c-6dd0645445fe.png)

Also, the Protege log file for loading the ontology is accessible in their UI via Window -> Show log... The Protege log also contains load errors, e.g.:

```
Level:       ERROR
Time:        1511982010664
Message:     Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error1 for type Class
```

According to [this wiki page](https://protegewiki.stanford.edu/wiki/Protege4ErrorClasses) on the Protege Wiki, these "Error" classes are generated by the OWL API and are a result of an invalid OWL document.

I think the starting point for tracking down where these errors live is to look at the Protege log file in more detail. Each of the ERROR blocks in the log file are followed by corresponding INFO blocks about unparsed triples:

```
Level:       ERROR
Time:        1511982023056
Message:     Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error6 for type Class

Level:       ERROR
Time:        1511982023057
Message:     Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error7 for type Class

Level:       ERROR
Time:        1511982023057
Message:     Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error8 for type Class

Level:       ERROR
Time:        1511982023058
Message:     Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error9 for type Class

Level:       ERROR
Time:        1511982023058
Message:     Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error10 for type Class

Level:       ERROR
Time:        1511982023058
Message:     Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error11 for type Class

Level:       ERROR
Time:        1511982023059
Message:     Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error12 for type Class

Level:       INFO
Time:        1511982023059
Message:     Unparsed triple: _:genid-nodeid-node1c04idg9kx6 -> http://www.w3.org/2002/07/owl#onProperty -> http://sweetontology.net/relaMath/hasWeightedEdge

Level:       INFO
Time:        1511982023060
Message:     Unparsed triple: _:genid-nodeid-node1c04idg9kx5 -> http://www.w3.org/2002/07/owl#onProperty -> http://sweetontology.net/relaMath/hasVertex

Level:       INFO
Time:        1511982023060
Message:     Unparsed triple: _:genid-nodeid-node1c04idg9kx2 -> http://www.w3.org/2002/07/owl#onProperty -> http://sweetontology.net/relaMath/hasArc

Level:       INFO
Time:        1511982023060
Message:     Unparsed triple: _:genid-nodeid-node1c04idg9kx1 -> http://www.w3.org/2002/07/owl#onProperty -> http://sweetontology.net/relaMath/hasOrderedVertexPair

Level:       INFO
Time:        1511982023060
Message:     Unparsed triple: _:genid-nodeid-node1c04idg9kx4 -> http://www.w3.org/2002/07/owl#onProperty -> http://sweetontology.net/relaMath/hasEdge

Level:       INFO
Time:        1511982023060
Message:     Unparsed triple: _:genid-nodeid-node1c04idg9kx3 -> http://www.w3.org/2002/07/owl#onProperty -> http://sweetontology.net/relaMath/hasUnorderedVertexPair

Level:       INFO
Time:        1511982023060
Message:     Unparsed triple: _:genid-nodeid-node1c04idg9kx10 -> http://www.w3.org/2002/07/owl#onProperty -> http://sweetontology.net/relaMath/hasWeight
```

In the above example, I don't know offhand why these triples in relaMath cause issues. Someone in the Protege group might be able to help with this.

**Comment by carueda** [comment]
> It's possible this is related to the fact the root ontology (http://sweetontology.net/sweetAll) #includes all the many individual ontologies

I don't see any issue with this "strategy" per se;  the "master" file simply imports all the other ontologies (some directly and others indirectly via nested imports).

I recently did a similar exercise (with Protégé 5.2.0), please see https://github.com/ESIPFed/sweet/issues/57.  I noticed a number of errors, but only 2 specifically involving SWEET definitions, basically that `http://sweetontology.net/relaMath/hasDimension` is being defined as both a DataProperty and ObjectProperty. Please note, my focus was mainly on exercising the resolution of the ontologies from the COR-enabled `http://sweetontology.net` location, but I took the chance to capture an entry as a heads-up for the SWEET development team.

**Comment by lewismc** [comment]
This has actually been a long standing issue whilst using Protege to view SWEET. Would be really nice to track down but I don't have any suggestions atm folks sorry.

**Comment by jvendetti** [comment]
Here's the discussion on Protege's user support mailing list: http://protege-project.136.n4.nabble.com/Debugging-owlapi-errors-on-SWEET-ontology-td4664108.html.

**Comment by graybeal** [comment]
Problem has been fixed on the SWEET side. BioPortal should be loading normally now with respect to this problem.
