### ISSUE TITLE
Biblioportal: change blue background colors to red

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#59]
Initially requested by the Stanford Library in #55:

"Can you change the blue color of the banner bar to red? _More accurately, change all the blue background to red._"

Desired hex color value: #B1040E.

**Comment by jvendetti** [comment]
Hi @michelleif. To follow is a screen shot from my local development environment that depicts the red background color for the top navigation bar. 

![screenshot 2017-12-05 13 37 10](https://user-images.githubusercontent.com/1696923/33633171-b8bb7444-d9c4-11e7-90c4-6394f483b6b1.png)

Is this what you were requesting? I'm a bit unclear on the comment of "change all the blue background to red". Are there other components in the user interface besides the top navigation bar that you're referring to?

Also, what is the desired appearance for ontology summary pages? Those pages have both a blue top navigation bar, and a blue main page background, e.g.:

![screenshot 2017-12-05 13 50 15](https://user-images.githubusercontent.com/1696923/33633223-e3830bba-d9c4-11e7-8d79-31cbec511eb7.png)

**Comment by michelleif** [comment]
Hi Jennifer,
What I meant by that comment was I realized that it's not just the banner that's blue, but as you point out, there's a blue background when you're looking at ontology pages. Can we change the blue page background to red also?

**Comment by jvendetti** [comment]
Thanks for the clarification @michelleif. Yes, this is possible for the ontology summary pages:

![screenshot 2017-12-06 15 33 08](https://user-images.githubusercontent.com/1696923/33690977-d2330e7e-da9a-11e7-84dd-5407ab47aa26.png)

**Comment by jvendetti** [comment]
@alexskr - as discussed earlier this week, in order to meet the Dec. 11th deadline, you can manually change two of the source files in the Biblioportal instance to make the background colors for the top navigation bar and ontology summary pages red. The hex color values need to be changed from #234979 to #B1040E on the following lines:

_bootstrap_and_overrides.css.scss_
[line 29](https://github.com/ncbo/bioportal_web_ui/blob/master/app/assets/stylesheets/bootstrap_and_overrides.css.scss#L29)

__ontology_viewer.html.haml_
[line 26](https://github.com/ncbo/bioportal_web_ui/blob/master/app/views/layouts/_ontology_viewer.html.haml#L26)
[line 27](https://github.com/ncbo/bioportal_web_ui/blob/master/app/views/layouts/_ontology_viewer.html.haml#L27)
[line 28](https://github.com/ncbo/bioportal_web_ui/blob/master/app/views/layouts/_ontology_viewer.html.haml#L28)
[line 69](https://github.com/ncbo/bioportal_web_ui/blob/master/app/views/layouts/_ontology_viewer.html.haml#L69)

I'll go on record in this issue to say that if any other code changes need to occur, we should move away from this method of manually changing files on their appliance instance to a fork of the [bioportal_web_ui](https://github.com/ncbo/bioportal_web_ui) project for Biblioportal.

**Comment by alexskr** [comment]
css and layout changes are in place.

**Comment by michelleif** [comment]
Hi,

I had an ontology CARRIERS-MADSRDF in Biblioportal that seems to have disappeared. I hope I didn't delete it by mistake. I can always reload it but am trying to figure out what happened to it.

Do you have any logs that would show if and when it was deleted?

Thank you!

Michelle


________________________________

**Comment by graybeal** [comment]
Michelle,

There's a separate long email thread about CARRIERS that you were on. Can you contact Jennifer and me offline to talk about how your request relates to that email?

John
