### ISSUE TITLE
delete NAMKHOA ontology

### ISSUE THREAD

**Issue by alexskr** [ncbo/bioportal-project#72]
Error refreshing ontologies report - Goo::Base::AttributeNotLoaded: Attribute `submissionId` is not loaded for //data.bioontology.org/ontologies/NAMKHOA/submissions/10. Loaded attributes: #.

**Comment by jvendetti** [comment]
Trying to delete this ontology via an ncbo_cron console session failed with:

```
ArgumentError: To load attributes the resource must be persistent
from /srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.3.0/bundler/gems/goo-158392d6b690/lib/goo/sparql/queries.rb:351:in `block in model_load_sliced’
```

I investigated and found several corrupt submission objects attached to the ontology. Some I was able to delete manually via the ncbo_cron console. Others I had to issue curl commands directly to 4store, e.g.:

```
curl -i -d "update=DELETE+{+<http://data.bioontology.org/ontologies/NAMKHOA/submissions/10>+?p+?o+}+WHERE+{+<http://data.bioontology.org/ontologies/NAMKHOA/submissions/10>+?p+?o+}" "http://ncboprod-4store1.stanford.edu:8080/update/"

HTTP/1.0 200 OK
Server: 4s-httpd/v1.1.5-122-g1788d29
Content-Type: text/plain; charset=utf-8
```

The ontology and all associated submissions have been deleted.
