### ISSUE TITLE
update admin user for BHF and AIDSONT ontologies

### ISSUE THREAD

**Issue by alexskr** [ncbo/bioportal-project#75]
BHF and AIDSONT ontologies have non-existing user listed as admin.

**Comment by jvendetti** [comment]
@alexskr - I don't see BHF in BioPortal. Can you clarify?

AIDSONT is fixed. Added HFBnew and HanfeiBaoOnt as administrators (these accounts are associated with the same email address).

**Comment by alexskr** [comment]
https://bioportal.bioontology.org/ontologies/BHF

**Comment by jvendetti** [comment]
Ah - OK. I wasn't able to see it w/out first clearing the caches. Can see it now though. Fixed the administrator to Hanfei's active accounts.
