### ISSUE TITLE
Require SSL on data.bioontology.org

### ISSUE THREAD

**Issue by graybeal** [ncbo/bioportal-project#83]
Make data.bioontology.org access prevent access via http directly. Anyone entering an http://data.bioontology.org should be redirected to the secure https. 

We will want to announce the change a few months in advance, so people have time to make the change in their software.

**Comment by graybeal** [comment]
Note that no existing IRIs or IRI generation should be affected—this just forwards the existing IRIs to the secure https address, which we then need to respond to with the original content.

**Comment by alexskr** [comment]
completed
