### ISSUE TITLE
Load UMLS 2018 AB

### ISSUE THREAD

**Issue by graybeal** [ncbo/bioportal-project#97]
Coming soon to ontology outlets everywhere.

Related task: #81

**Comment by mdorf** [comment]
Please remove NDFRT and add MEDRT, per ncbo/umls2rdf/issues/27

**Comment by alexskr** [comment]
looks like NDFRT is still included in 2018AB but will not appear in 2019AA or subsequent releases.  So should we keep in for 2018AB and remove it in 2019AA?

**Comment by graybeal** [comment]
that makes sense to me. keep it consistent with UMLS release.

**Comment by alexskr** [comment]
2018AB is loaded and NDFRT will not be removed until 2019AA
